IMPOSSIBLE_EXCEPTION = "The impossible has happened. The world is ending. God save the King!"
SESSION_EXISTS = "A slot already exists for {date} from {start_time} to {end_time} at {location}"
SESSION_NOT_FOUND = "No session exist for {date} from {start_time} to {end_time} at {location}"
SLOT_NOT_FOUND = "Slot {slot_idx} for {date} at {location} does not exist"
SLOT_FULL = "Slot {slot_idx} for {date} at {location} is full"
